# -*- coding: utf-8 -*-
"""sales.analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15K1rHDNOgBjqXRZ04SMxMoq1j-rQ2qC-
"""

import pandas as pd
import numpy as np

df = pd.read_csv('online_sales_dataset.csv')


df.head()


df.info()


df.isnull().sum()


df = df.drop_duplicates()


df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])


df['CustomerID'] = df['CustomerID'].fillna(0)


df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]


df['Discount'] = df['Discount'].fillna(0)

# Revenue column
df['Revenue'] = df['Quantity'] * df['UnitPrice']

# Year column
df['Year'] = df['InvoiceDate'].dt.year

#  Month column
df['Month'] = df['InvoiceDate'].dt.month

# Month Name column
df['MonthName'] = df['InvoiceDate'].dt.month_name()


df.describe()

df.head()


df.to_csv('clean_online_sales.csv', index=False)

print("Preprocessed dataset saved as clean_online_sales.csv")

from google.colab import files

files.download('clean_online_sales.csv')